import re

from playwright.sync_api import expect


def test_department_flow(logged_in_page) -> None:
    page = logged_in_page
    print("Prepare to record Department flow.")

    # Navigate to dashboard to ensure clean page state
    page.goto("https://qa.hrmgenie.outstrive.co/")
    page.wait_for_load_state("networkidle")
    
    page.locator("div").filter(has_text=re.compile(r"^HRM Configuration$")).click()
    page.get_by_role("button", name="Department").click()
    page.get_by_role("textbox", name="Search by department").click()
    page.get_by_role("textbox", name="Search by department").fill("")
    page.get_by_role("button", name="Sort").click()
    page.get_by_role("button", name="Sort").click()
    page.get_by_role("button", name="Add Department").click()
    page.get_by_role("textbox", name="e.g., Marketing").fill("Bala")
    page.get_by_role("textbox", name="e.g., Marketing").click()
    page.get_by_role("button", name="Select BUHead").click()
    page.get_by_role("button", name="Gattu Ashwitha").click()
    page.get_by_role("button", name="Select CXO").click()
    page.get_by_role("button", name="Syed khaja Irfanuddin").click()
    page.get_by_role("switch").click()
    page.get_by_role("switch").click()
    page.get_by_role("button", name="Add Department").click()
    page.locator(".absolute.right-2").click()
    page.get_by_role("button", name="Add Department").click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("button", name="Add Department").click()
    page.get_by_role("button", name="Cancel").click()
    page.locator("div:nth-child(3) > .flex.items-start > .flex.items-center.gap-2 > button:nth-child(3)").click()
    page.get_by_role("button", name="Add Sub Department").nth(2).click()
    page.get_by_role("textbox", name="e.g., Development").click()
    page.get_by_role("textbox", name="e.g., Development").fill("Kiran")
    page.get_by_role("switch").click()
    page.get_by_role("switch").click()
    page.get_by_role("button", name="Add Sub Department").click()
    page.locator(".absolute.right-2").click()
    page.get_by_role("button", name="Add Sub Department").nth(2).click()
    page.get_by_role("button", name="Close").click()
    page.get_by_role("button", name="Add Sub Department").nth(2).click()
    page.get_by_role("button", name="Cancel").click()
    page.locator(".col-span-1.bg-white.rounded-xl > .flex.items-start > div:nth-child(2) > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.hover\\:bg-accent").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Sub Department Name \*$")).click()
    page.get_by_role("textbox", name="e.g., Development").click()
    page.get_by_role("textbox", name="e.g., Development").fill("Kiran balaa")
    page.get_by_role("button", name="Update Sub Department").click()
    page.locator(".absolute.right-2").click()
    page.locator(".col-span-1.bg-white.px-8.py-5.rounded-3xl.border.overflow-hidden.max-h-\\[600px\\] > div > .flex.items-center.gap-2 > button").first.click()
    page.get_by_role("textbox", name="e.g., Marketing").click()
    page.get_by_role("textbox", name="e.g., Marketing").fill("Bala balaa")
    page.get_by_role("button", name="Update Department").click()
    page.locator(".absolute.right-2").click()
    page.locator(".col-span-1.bg-white.px-8.py-5.rounded-3xl.border.overflow-hidden.max-h-\\[600px\\] > div > .flex.items-center.gap-2 > button").first.click()
    page.get_by_role("button", name="Close").click()
    page.locator(".col-span-1.bg-white.px-8.py-5.rounded-3xl.border.overflow-hidden.max-h-\\[600px\\] > div > .flex.items-center.gap-2 > button").first.click()
    page.get_by_role("button", name="Cancel").click()
    page.locator(".col-span-1.bg-white.px-8.py-5.rounded-3xl.border.overflow-hidden.max-h-\\[600px\\] > div > .flex.items-center.gap-2 > button:nth-child(3)").click()
    page.get_by_role("tab", name="Practices").click()
    page.get_by_role("button", name="Add Practice").click()
    page.get_by_role("textbox", name="e.g., MS").fill("Bala sarma")
    page.get_by_role("textbox", name="e.g., MS").click()
    page.get_by_role("textbox", name="e.g., Managed Services").click()
    page.get_by_role("textbox", name="e.g., Managed Services").fill("Bala Subbu")
    page.get_by_role("button", name="Select departments to link").click()
    page.get_by_role("button", name="Logistics").click()
    page.get_by_role("button", name="Logistics").first.click()
    page.get_by_role("switch").click()
    page.get_by_role("switch").click()
    page.get_by_role("button", name="Add Practice").click()
    page.locator(".absolute.right-2").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > button").first.click()
    page.get_by_role("textbox", name="e.g., MS").click()
    page.get_by_role("textbox", name="e.g., MS").fill("Bala sarma bala")
    page.get_by_role("textbox", name="e.g., Managed Services").click()
    page.get_by_role("textbox", name="e.g., Managed Services").fill("Bala Subbu bala")
    page.get_by_role("button", name="Update Practice").click()
    page.locator(".absolute.right-2").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > button").first.click()
    page.get_by_role("button", name="Close").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > button").first.click()
    page.get_by_role("button", name="Cancel").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").click()
    page.get_by_role("button", name="Cancel").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").click()
    page.get_by_role("button", name="Close").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").click()
    page.get_by_role("button", name="Delete").click()
    page.locator(".absolute.right-2").click()
    page.get_by_role("button", name="Close").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > button").first.click()
    page.get_by_role("button", name="Logistics").click()
    page.get_by_role("button", name="Logistics").nth(1).click()
    page.get_by_role("button", name="Select departments to link").click()
    page.get_by_role("button", name="Update Practice").click()
    page.locator(".absolute.right-2").click()
    page.locator("div:nth-child(2) > .p-0 > .p-6 > .flex.items-start > .flex.items-center.gap-2 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").click()
    page.get_by_role("button", name="Delete").click()
    page.locator(".absolute.right-2").click()
    page.get_by_role("tab", name="Department", exact=True).click()
    page.locator(".grid > div:nth-child(3) > div").first.click()
    page.locator("div:nth-child(3) > div > .flex.items-center.gap-2 > button:nth-child(3)").click()
    page.locator(".col-span-1.bg-white.rounded-xl > .flex.items-start > div:nth-child(2) > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").first.click()
    page.get_by_role("button", name="Delete").click()
    page.locator(".absolute.right-2").click()
    page.locator(".col-span-1.bg-white.px-8.py-5.rounded-3xl.border.overflow-hidden.max-h-\\[600px\\] > .flex.items-start > .flex.items-center.gap-2 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").click()
    page.get_by_role("button", name="Delete").click()
    page.locator(".absolute.right-2").click()
    page.get_by_role("tab", name="Sub Department & Designation").click()
    page.get_by_role("button", name="Add Designation").first.click()
    page.get_by_role("textbox", name="e.g., Senior UX Designer").click()
    page.get_by_role("textbox", name="e.g., Senior UX Designer").fill("Test Engineet Test")
    page.get_by_placeholder("0").first.click()
    page.get_by_placeholder("0").first.fill("3")
    page.get_by_placeholder("0").nth(1).click()
    page.get_by_placeholder("0").nth(1).fill("0")
    page.get_by_role("textbox", name="Type and press Enter to add").first.click()
    page.get_by_role("textbox", name="Type and press Enter to add").first.fill("Testing Bala Testing")
    page.get_by_role("textbox", name="Type and press Enter to add").nth(1).click()
    page.get_by_role("textbox", name="Type and press Enter to add").nth(1).fill("Automation c#")
    page.get_by_role("switch").click()
    page.get_by_role("switch").click()
    page.get_by_role("button", name="Add Designation").click()
    page.get_by_placeholder("0").nth(1).click()
    page.get_by_placeholder("0").nth(1).fill("5")
    page.get_by_role("button", name="Add Designation").click()
    page.locator(".absolute.right-2").click()
    page.locator("div:nth-child(2) > .flex.justify-between > .flex.items-center.gap-3 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.hover\\:bg-accent").first.click()
    page.get_by_role("button", name="Close").click()
    page.locator("div:nth-child(2) > .flex.justify-between > .flex.items-center.gap-3 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.hover\\:bg-accent").first.click()
    page.get_by_role("button", name="Cancel").click()
    page.locator("div:nth-child(2) > .flex.justify-between > .flex.items-center.gap-3 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.hover\\:bg-accent").first.click()
    page.get_by_role("textbox", name="Type and press Enter to add").first.click()
    page.get_by_role("textbox", name="Type and press Enter to add").first.fill("Engineering")
    page.get_by_role("textbox", name="Type and press Enter to add").nth(1).click()
    page.get_by_role("textbox", name="Type and press Enter to add").nth(1).fill("Engineer")
    page.get_by_role("button", name="Save Changes").click()
    page.locator(".absolute.right-2").click()
    page.locator("div:nth-child(2) > .flex.justify-between > .flex.items-center.gap-3 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").first.click()
    page.get_by_role("button", name="Close").click()
    page.locator("div:nth-child(2) > .flex.justify-between > .flex.items-center.gap-3 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").first.click()
    page.get_by_role("button", name="Cancel").click()
    page.locator("div:nth-child(2) > .flex.justify-between > .flex.items-center.gap-3 > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-xl.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.h-9.w-9.text-red-500").first.click()
    page.get_by_role("button", name="Delete").click()
    page.locator(".absolute.right-2").click()
    # Safely paginate and toggle department view options if available
    for page_num in [2, 3, 4, 5]:
        page_button = page.get_by_text(str(page_num), exact=True)
        if page_button.count() > 0:
            page_button.click()
            page.wait_for_timeout(500)
        else:
            print(f"Pagination page {page_num} not available, skipping.")
    nav_buttons = [
        ("Go to previous page", 1),
        ("Go to next page", 1),
        ("Go to previous page", 3),
        ("Go to previous page", 1),
        ("Go to previous page", 1)
    ]
    for button_label, _ in nav_buttons:
        nav_btn = page.get_by_label(button_label)
        if nav_btn.count() > 0 and nav_btn.get_attribute("aria-disabled") != "true":
            nav_btn.click()
            page.wait_for_timeout(300)
        else:
            print(f"Navigation button '{button_label}' is disabled or not available, skipping.")
    page_sizes = ["10", "20", "30", "40"]
    for size in page_sizes:
        combobox = page.get_by_role("combobox").filter(has_text=size)
        if combobox.count() > 0:
            combobox.click()
            page.wait_for_timeout(300)
        else:
            option = page.get_by_text(size, exact=True)
            if option.count() > 0:
                option.click()
                page.wait_for_timeout(300)
            else:
                print(f"Page size option '{size}' not available, skipping.")
    page.get_by_role("main").click()
